INSERT INTO DEPARTMENT VALUES (1,'IT', 'CO');

INSERT INTO EMPLOYEE VALUES (1,'Noel');
INSERT INTO EMPLOYEE VALUES (2,'PEPE');

INSERT INTO DEPARTMENT_EMPLOYEE  VALUES (1,1);
INSERT INTO DEPARTMENT_EMPLOYEE VALUES (1,2);

